### ISSUE TITLE
ODM2 Vocabulary Site is down??

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/ODM2#141]
http://vocabulary.odm2.org appears to be down. Anyone else experiencing this problem? Thanks.

**Comment by miguelcleon** [comment]
@lsetiawan yes, it appears to be down, I noticed this on Friday, I should have made an issue like this.

**Comment by horsburgh** [comment]
Thanks for the heads up guys. On Friday I replaced the batteries in the UPS system that the host on which this virtual machine is running is plugged into. I've been having problems with the host going down every time the power would bump in the building because the UPS batteries were dead - the host comes back, but the virtual machines on it don't.

I just started the machine and the site is back up. I didn't notice it was down while I was doing maintenance on Friday or I would have started it then.

Please keep an eye on it. If this continues to be a problem I will speed up my plan to move this VM up to campus.

**Comment by lsetiawan** [comment]
Great! It's working now. Thanks @horsburgh 😄  I'll keep an eye out!

**Comment by emiliom** [comment]
Thanks, all! Just adding the picky comment that in the future it's better to report problems with the ODM2 vocab system on its dedicated repository: https://github.com/ODM2/ODM2ControlledVocabularies
@horsburgh will see the issue either way, but it's a bit cleaner and easier to track when posting to the most appropriate repo

**Comment by lsetiawan** [comment]
Ah. My bad. Didn't realize that's there. Thanks!
