### ISSUE TITLE
Consider UDUNITS or other Units systems

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2#43]
Right now Units in ODM2 are the same as in ODM 1.1.1.  An enhancement might be to consider other specifications for Units that might better support units conversions, etc.

**Comment by aufdenkampe** [comment]
Closing this "lost" issue, because of all the work that we did to create an ODM2_Units CV based on QUDT (including water quality/CHEBI extension by Simmons et al.), CUAHSI, UD Units, UCUM, USGS SRS Names, and AI Informatics. This work was done in the the [ODM2_UnitsTable-Combined-QUDT-CUAHSI](https://docs.google.com/spreadsheets/d/1sE0PZ2sJxVx1fVGp_JnlpQFCCKRMKx6RWgYLPkkUmAw/edit#gid=652835034) Google Doc and the [ODM2_UnitsTypeCV](https://docs.google.com/spreadsheets/d/1Uj0pp804F1j-zXTbg-UGoXItpw5FBk5HfX88tjMFsIM/edit#gid=2036799299) Google Doc. The later was elevated to an official ODM2 CV at http://vocabulary.odm2.org/unitstype/, but the former was not.

Much of this work, along with remaining issues, was recently described and referenced in https://github.com/ODM2/ODM2ControlledVocabularies/issues/34.
